"""add_themes_projects_members_vocabulary

Revision ID: ae525721359b
Revises: 724191df3d68
Create Date: 2026-09-07 15:48:20.503463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae525721359b'
down_revision: Union[str, Sequence[str], None] = '724191df3d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect as sa_inspect, text as _text
    conn = op.get_bind()
    # batch_alter_table は DROP TABLE → RENAME の手順を踏むため、
    # foreign_keys=ON のままだと CASCADE DELETE でデータが消える。
    # 念のためここでも OFF にする（env.py でも設定済みだが二重対策）。
    conn.execute(_text("PRAGMA foreign_keys=OFF"))
    existing_tables = sa_inspect(conn).get_table_names()

    if 'themes' not in existing_tables:
        op.create_table('themes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'projects' not in existing_tables:
        op.create_table('projects',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('theme_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'project_members' not in existing_tables:
        op.create_table('project_members',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('company', sa.String(length=200), nullable=True),
        sa.Column('job_title', sa.String(length=200), nullable=True),
        sa.Column('project_role', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'project_vocabulary' not in existing_tables:
        op.create_table('project_vocabulary',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('word', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    # Add columns to existing tables (idempotent: check before adding)
    transcripts_cols = {c['name'] for c in sa_inspect(conn).get_columns('transcripts')}
    if 'project_id' not in transcripts_cols:
        with op.batch_alter_table('transcripts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_transcripts_project_id', 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    users_cols = {c['name'] for c in sa_inspect(conn).get_columns('users')}
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'company' not in users_cols:
            batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=True))
        if 'job_title' not in users_cols:
            batch_op.add_column(sa.Column('job_title', sa.String(length=200), nullable=True))

    conn.execute(_text("PRAGMA foreign_keys=ON"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('job_title')
        batch_op.drop_column('company')

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transcripts_project_id', type_='foreignkey')
        batch_op.drop_column('project_id')

    op.drop_table('project_vocabulary')
    op.drop_table('project_members')
    op.drop_table('projects')
    op.drop_table('themes')
    # ### end Alembic commands ###
